# Generated by Django 2.1.7 on 2019-02-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bCode', models.IntegerField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('classno', models.IntegerField()),
                ('loanCnt', models.IntegerField()),
                ('bImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookAdmin',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Book')),
            ],
            bases=('pages.book',),
        ),
    ]
