# Generated by Django 2.1.7 on 2019-02-27 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('bCode', models.AutoField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('classno', models.IntegerField()),
                ('loanCnt', models.IntegerField()),
                ('bImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='classno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classno', models.IntegerField()),
                ('cName', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('lCode', models.AutoField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('bImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('birth', models.IntegerField()),
                ('mName', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('passwd', models.CharField(max_length=20)),
                ('wImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='recommendations',
            fields=[
                ('rCode', models.AutoField(primary_key=True, serialize=False)),
                ('bName', models.CharField(max_length=255)),
                ('bImage', models.CharField(max_length=255)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.members')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypage.members'),
        ),
    ]
